apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::442940292368:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-tq7F2TanIGXA
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::442940292368:user/suresh
      username: suresh

    - groups:  
      - roboshop-admin
      userarn: arn:aws:iam::442940292368:user/ramesh
      username: ramesh

     - groups:  
      - trainee-group
      userarn: arn:aws:iam::442940292368:user/ram
      username: ram

     - groups:  
      - trainee-group
      userarn: arn:aws:iam::442940292368:user/ram
      username: sam 
      
    
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-03T01:12:48Z"
  name: aws-auth
  namespace: kube-system
  uid: 38553540-2b04-4d1b-850e-31cc150246c5
